# -*- coding: utf-8 -*-
"""DHC-6221_ Eman_Faris.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TuoYXJhNJuhU8-8VIo2wPzTmw3bVTDNx

# **TASK 1: Exploring & Visualizing Iris Dataset**
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = sns.load_dataset('iris')

df.shape
df.columns
df.head()
df.info()
df.describe()

sns.scatterplot(x='sepal_length', y='petal_length', hue='species', data=df)

plt.savefig('scatter_plot.png', dpi=300, bbox_inches='tight')
plt.show()

df.hist(figsize=(8,6))
plt.show()

sns.boxplot(data=df)
plt.show()

"""## Outlier Detection"""

numerical_cols = df.select_dtypes(include=['float64']).columns

plt.figure(figsize=(15, 10))
for i, col in enumerate(numerical_cols):
    plt.subplot(2, 2, i + 1) # Assuming there are 4 numerical columns
    sns.boxplot(x='species', y=col, data=df, hue='species', palette='viridis', legend=False)
    plt.title(f'Box Plot of {col} by Species')
    plt.xlabel('Species')
    plt.ylabel(col)
plt.tight_layout()
plt.show()

"""## Median Comparison Across Species"""

median_by_species = df.groupby('species')[numerical_cols].median()
display(median_by_species)

"""### Interpretation of Median Comparison

From the median values, we can observe distinct characteristics for each Iris species:

*   **Iris-setosa**: This species generally has shorter sepal lengths, wider sepal widths, and significantly smaller petal lengths and widths compared to the other two species.
*   **Iris-versicolor**: This species falls in the middle for most features. Its sepal and petal measurements are larger than setosa but generally smaller than virginica.
*   **Iris-virginica**: This species typically exhibits the largest sepal lengths, petal lengths, and petal widths. Its sepal width is often comparable to or slightly less than setosa's, but it's generally wider than versicolor.

These median comparisons highlight the features that are most discriminative between the Iris species, particularly petal length and width, which show clear separation.

# **TASK 2: Stock Price Prediction**
"""

import yfinance as yf

data = yf.download('AAPL', start='2020-01-01', end='2023-01-01')

df = data[['Open', 'High', 'Low', 'Volume', 'Close']]
df['Target'] = df['Close'].shift(-1)
df.dropna(inplace=True)

df.shape
df.columns
df.head()
df.info()
df.describe()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X = df[['Open','High','Low','Volume']]
y = df['Target']

X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=False)

model = LinearRegression()
model.fit(X_train, y_train)

preds = model.predict(X_test)

import matplotlib.pyplot as plt

plt.plot(y_test.values, label='Actual')
plt.plot(preds, label='Predicted')
plt.legend()

"""# **Interpretation**

**Overlapping Lines (Good Prediction):** When the blue and orange lines closely align or overlap, it signifies that your model's predictions are highly accurate and closely match the actual observed stock prices.

**Big Gaps (Poor Model):** Large discrepancies or 'big gaps' between the actual and predicted lines indicate that the model is not performing well at those points, as its predictions deviate significantly from the true stock values.

**Insights from the plot of the Stock Price Prediction Model:**

Looking at the generated plot, it can be observed  that the predicted prices (orange line) generally follow the trend of the actual prices (blue line). This suggests that the linear regression model has learned some underlying patterns in the stock movement. However, there are also noticeable gaps, particularly during periods of higher volatility or sharp changes in price. These gaps indicate that while the model captures the overall direction, it struggles to precisely predict the magnitude of these changes or sudden shifts. Therefore, while it provides a reasonable general trend prediction, there is room for improvement in its accuracy for specific price points, especially during turbulent market conditions.

# **TASK 3: Heart Disease Prediction**
"""

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('heart.csv')

df.shape
df.columns
df.head()
df.info()
df.describe()

sns.countplot(x='target', data=df)
sns.heatmap(df.corr(), annot=True)

from sklearn.linear_model import LogisticRegression

X = df.drop('target', axis=1)
y = df['target']

model = LogisticRegression()
model.fit(X, y)

from sklearn.metrics import accuracy_score, confusion_matrix

preds = model.predict(X)

accuracy_score(y, preds)
confusion_matrix(y, preds)

"""# **Interpretations and Insights for Heart Disease Prediction Model**

### 1. Exploratory Data Analysis (EDA) Insights:

*   **Data Structure:** The dataset contains 1025 entries and 14 columns, with no missing values, which is good for model training.
*   **Feature Types:** Most features are integers, but `oldpeak` is a float. It's important to understand the meaning of these categorical and numerical features for domain-specific insights.
*   **Target Distribution:** The `sns.countplot(x='target', data=df)` plot (from a previous cell) would show the distribution of the 'target' variable. Given `df.describe()` shows a mean of `0.513` for `target`, it suggests a relatively balanced dataset between patients with and without heart disease, which is beneficial for classification tasks.
*   **Correlations:** The heatmap `sns.heatmap(df.corr(), annot=True)` (from a previous cell) provides insights into relationships between features and with the target. Features highly correlated with 'target' are usually strong predictors (e.g., `cp`, `thalach`, `slope` often show positive correlation with heart disease, while `exang` and `oldpeak` might show negative correlation). Highly correlated features among themselves might indicate multicollinearity, which some models are sensitive to.

### 2. Confusion Matrix and Model Evaluation:

The confusion matrix for the Logistic Regression model is `[[391, 108], [47, 479]]`.

*   **True Negatives (TN): 391** - The model correctly predicted 391 cases as *not* having heart disease.
*   **False Positives (FP): 108** - The model incorrectly predicted 108 cases as *having* heart disease when they did not (Type I error).
*   **False Negatives (FN): 47** - The model incorrectly predicted 47 cases as *not* having heart disease when they actually did (Type II error).
*   **True Positives (TP): 479** - The model correctly predicted 479 cases as *having* heart disease.

From these values, we can calculate key metrics:

*   **Accuracy:** `(TN + TP) / Total = (391 + 479) / (391 + 108 + 47 + 479) = 870 / 1025 ≈ 0.849` (84.9% accuracy).
*   **Recall (Sensitivity):** `TP / (TP + FN) = 479 / (479 + 47) = 479 / 526 ≈ 0.911` (91.1% recall for heart disease).
*   **Precision:** `TP / (TP + FP) = 479 / (479 + 108) = 479 / 587 ≈ 0.816` (81.6% precision for heart disease).

### 3. Interpretation with Emphasis on Recall (Medical Context):

As you noted, **high recall is more important than accuracy in medical tasks**, especially when dealing with potentially life-threatening conditions like heart disease. Here's why and how our model performs:

*   **Importance of Recall:** In heart disease prediction, a False Negative (missing a patient who actually has heart disease) can have severe, even fatal, consequences. It's generally preferable to have a False Positive (incorrectly diagnosing someone with heart disease, leading to further tests) than a False Negative. High recall ensures that a high proportion of actual positive cases are identified by the model.

*   **Model Performance:** Our Logistic Regression model achieved a **recall of approximately 91.1%**. This is a strong result in the context of heart disease prediction, indicating that the model is quite effective at identifying individuals who genuinely have the disease. It minimizes the risk of overlooking sick patients.

*   **Trade-offs:** While recall is high, the precision (81.6%) is a bit lower, meaning that about 18.4% of the patients predicted to have heart disease by the model actually do not (False Positives). This implies that some healthy individuals might be flagged for further examination. In a medical context, this trade-off is often acceptable, as missing a true positive (low recall) is typically considered a more critical error than generating a false alarm (low precision).

### 4. Regression (Logistic Regression) Specifics:

*   Logistic Regression is a suitable choice for binary classification problems like heart disease prediction. It models the probability of a binary outcome. The warning `ConvergenceWarning: lbfgs failed to converge (status=1): STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.` suggests that the model might not have fully converged. This could sometimes be addressed by scaling the data (e.g., using `StandardScaler`) or increasing the `max_iter` parameter in the `LogisticRegression` constructor. Addressing this might slightly improve model performance, though the current recall is already quite good.

In summary, the model shows promising results, particularly in its ability to correctly identify a large proportion of patients with heart disease, aligning well with the critical need for high recall in medical diagnoses. Further improvements could involve addressing the convergence warning and exploring more advanced classification algorithms.

# **TASK 4: Health Chatbot (Prompt Engineering)**
"""

import openai

prompt = "Act like a helpful medical assistant. Answer safely: What causes sore throat?"

user_input = input("Enter your query: ")

if "emergency" in user_input:
    print("Please consult a doctor immediately.")

"""# **Interpretation:**

**1. Prompt Controls Tone and Persona:**

**Insight:**

The initial prompt, "Act like a helpful medical assistant. Answer safely: What causes sore throat?", is crucial. The phrase "Act like a helpful medical assistant" directly sets the persona and tone for the chatbot's responses. It guides the model to adopt a professional, empathetic, and informative demeanor, characteristic of a medical assistant, rather than a generic AI.


**Interpretation:**

This demonstrates how prompt engineering allows us to govern the style and character of the AI's output. By explicitly stating the desired persona, we can steer the conversation towards a more appropriate and trustworthy interaction, which is vital in sensitive domains like healthcare.


**2. Safety Prevents Harmful Advice:**

**Insight:**

 The conditional check if "emergency" in user_input: print("Please consult a doctor immediately.") is a fundamental safety mechanism. It's a hard-coded rule designed to prevent the chatbot from attempting to provide medical advice in situations that clearly require human intervention.


**Interpretation:**

In medical applications, the primary goal is 'do no harm'. While large language models can be highly informative, they are not substitutes for qualified medical professionals, especially in emergencies. This code snippet proactively handles critical keywords, redirecting the user to human experts and significantly mitigating the risk of providing inappropriate or dangerous automated advice.


**3. Good Prompts = Better Answers Than Complex Models (Contextualized):**


**Insight:**

 The idea that 'good prompts lead to better answers than complex models' highlights the power of clear, well-structured instructions. Even with a simple openai (or similar LLM) call, the quality of the prompt determines the utility of the response.


**Interpretation:**

In this task, the prompt "Act like a helpful medical assistant. Answer safely: What causes sore throat?" immediately frames the query, sets boundaries (safety), and directs the AI to a specific knowledge domain. This focus on the instruction given to the model, rather than just the underlying model's raw capability, can yield highly relevant and safe answers. It suggests that investing in refining prompts can often be more impactful for specific use cases than continuously chasing ever-larger or more complex AI models. A simple, well-guided model can outperform a complex, unguided one for targeted questions, especially when safety and context are paramount.

# **TASK 5: Mental Health Chatbot (Fine-Tuned)**
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('emotion-emotion_69k.csv')

df.shape
df.columns
df.head()
df.info()
df.describe()

from transformers import Trainer

input: "I feel anxious"
output: "I'm sorry you're feeling this way..."

"""# **TASK 6: House Price Prediction**"""

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('Housing.csv')

df.shape
df.columns
df.head()
df.info()
df.describe()

numeric_cols = df.select_dtypes(include=['int64', 'float64'])
categorical_cols = df.select_dtypes(include=['object'])

df[numeric_cols.columns] = numeric_cols.fillna(numeric_cols.mean())

df[categorical_cols.columns] = categorical_cols.fillna(categorical_cols.mode().iloc[0])

from sklearn.model_selection import train_test_split

X = df.drop('price', axis=1)
y = df['price']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

df.replace({'yes': 1, 'no': 0}, inplace=True)

df = pd.get_dummies(df, drop_first=True)

df.info()

from sklearn.model_selection import train_test_split

X = df.drop('price', axis=1)
y = df['price']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("MAE:", mae)
print("RMSE:", rmse)

import matplotlib.pyplot as plt

plt.scatter(y_test, y_pred)
plt.xlabel("Actual Prices")
plt.ylabel("Predicted Prices")
plt.title("Actual vs Predicted Prices")
plt.show()

df.select_dtypes(include='object').columns

"""# **Interpretation of the Results:**

# **1. Data Preprocessing:**
**bold text**
**Initial Data:**

 The dataset contained a mix of numerical (int64) and categorical (object) columns. There were no missing values after loading, which simplified the initial cleaning.

**Categorical Feature Handling:**


*   Binary categorical features like mainroad, guestroom,
basement, hotwaterheating, airconditioning, and prefarea were converted to numerical representations (1 for 'yes', 0 for 'no').
*   The furnishingstatus column, which is multi-categorical, was handled using one-hot encoding (pd.get_dummies), creating new binary columns(furnishingstatus_semi-furnished, furnishingstatus_unfurnished). This ensures that the linear regression model can correctly interpret these features.



# **2. Model Training:**

* **Feature and Target Split:** The price column was identified as the target variable (y), and all other processed columns were used as features (X).

* **Train-Test Split:** The data was split into training and testing sets (80% train, 20% test) to evaluate the model's performance on unseen data.
Model: A LinearRegression model was chosen and trained on the X_train and y_train data.

# **3. Model Evaluation:**
After making predictions on the test set (y_pred), the model's performance was evaluated using two common regression metrics:

* **Mean Absolute Error (MAE):** MAE: 970043.4039201637
 **Interpretation:** This means, on average, the model's predictions for house prices were off by approximately 970,043 units of currency (assuming the price unit is consistent, e.g., dollars). MAE gives a direct measure of the average magnitude of the errors.

* **Root Mean Squared Error (RMSE):** RMSE: 1324506.9
**Interpretation:** RMSE is approximately 1,324,506. This metric penalizes larger errors more heavily than MAE due to the squaring. It's often preferred when large errors are particularly undesirable.

**Overall Assessment of Metrics:** Both MAE and RMSE are quite high relative to the typical house prices in the dataset (which range from 1.75 million to 13.3 million, with a mean of 4.76 million). This suggests that the model's predictions are not very accurate, and there's significant room for improvement.

# **4. Actual vs. Predicted Prices Plot:**
* **Scatter Plot:** The scatter plot of Actual Prices (x-axis) vs. Predicted Prices (y-axis) helps visualize the model's performance.

* **Ideal Scenario:** In a perfect model, all points would lie exactly on a 45-degree diagonal line, meaning actual prices perfectly match predicted prices.

* **Observed Behavior:** The plot shows a noticeable spread of points around the theoretical diagonal line. While there's a general upward trend, indicating that the model attempts to predict higher prices for higher actual prices, the points are quite scattered. This scattering confirms the high MAE and RMSE values – the model's predictions frequently deviate significantly from the actual values.

**Overall Insights:**

* **Basic Linear Model:**
The Linear Regression model provides a foundational attempt at predicting house prices but demonstrates limited accuracy for this dataset.

* **Potential for Improvement:**
 The high error metrics and scattered plot indicate that the model is likely either too simple for the complexity of the house pricing problem or that important features (or feature interactions) are missing, or that the linear assumptions are not holding true for this data. The current model might not be robust enough to capture all the nuances of house pricing.


**Next Steps for Improvement:**
To improve the model's performance, you might consider:

* **Feature Engineering:** Creating new features from existing ones (e.g., interaction terms, polynomial features).

* **More Advanced Models:** Exploring other regression algorithms such as Ridge, Lasso, ElasticNet, Decision Trees, Random Forests, Gradient Boosting Machines (XGBoost, LightGBM), or Neural Networks.

* **Hyperparameter Tuning:** Optimizing the parameters of the chosen model.

* **Data Scaling:**
 Scaling numerical features can sometimes help linear models perform better.

* **Outlier Treatment:** Further investigating and handling outliers in the price or feature distributions.

* **Cross-Validation:** Using cross-validation techniques for more robust model evaluation
"""